
export const dbSetupScript = `
-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Profiles (Linked to Auth)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  role TEXT CHECK (role IN ('admin', 'employee')) DEFAULT 'employee',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Trigger to create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username, role)
  VALUES (new.id, split_part(new.email, '@', 1), 'employee');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 2. Store Settings
CREATE TABLE IF NOT EXISTS public.store_settings (
  id SERIAL PRIMARY KEY,
  store_name TEXT DEFAULT 'PijamaManager Pro',
  theme_color TEXT DEFAULT '#0ea5e9',
  max_installments INTEGER DEFAULT 6,
  payment_config JSONB DEFAULT '[]'::jsonb
);

-- 3. Clients
CREATE TABLE IF NOT EXISTS public.clients (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  full_name TEXT NOT NULL,
  cpf TEXT,
  phone TEXT,
  email TEXT,
  address TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Products (Parent)
CREATE TABLE IF NOT EXISTS public.products (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  nome TEXT NOT NULL,
  modelo TEXT,
  descricao TEXT,
  categoria TEXT,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Inventory (Children)
CREATE TABLE IF NOT EXISTS public.estoque_tamanhos (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  product_id UUID REFERENCES public.products(id) ON DELETE CASCADE,
  size TEXT NOT NULL,
  quantity INTEGER DEFAULT 0,
  price_cost DECIMAL(10,2) DEFAULT 0,
  price_sale DECIMAL(10,2) DEFAULT 0,
  sku TEXT,
  reference TEXT,
  UNIQUE(product_id, size)
);

-- 6. Sales & Quotes (Unified Head)
CREATE TABLE IF NOT EXISTS public.vendas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id UUID REFERENCES public.clients(id) ON DELETE SET NULL,
  user_id UUID REFERENCES auth.users(id),
  total_value DECIMAL(10,2) NOT NULL,
  payment_method TEXT, 
  payment_status TEXT CHECK (payment_status IN ('paid', 'pending', 'refunded', 'loss')),
  status_label TEXT CHECK (status_label IN ('Venda', 'Condicional', 'Baixa', 'Devolução')),
  payment_details JSONB,
  observacoes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Sale Items
CREATE TABLE IF NOT EXISTS public.venda_itens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id BIGINT REFERENCES public.vendas(id) ON DELETE CASCADE,
  product_variation_id UUID REFERENCES public.estoque_tamanhos(id),
  quantity INTEGER NOT NULL,
  unit_price DECIMAL(10,2) NOT NULL,
  original_cost DECIMAL(10,2) -- Snapshot for profit calc
);

-- RLS Policies (Basic Open for Demo Authenticated Users)
-- Drop existing policies first to avoid "policy already exists" errors
DROP POLICY IF EXISTS "Enable all for authenticated" ON profiles;
DROP POLICY IF EXISTS "Enable all for authenticated" ON clients;
DROP POLICY IF EXISTS "Enable all for authenticated" ON products;
DROP POLICY IF EXISTS "Enable all for authenticated" ON estoque_tamanhos;
DROP POLICY IF EXISTS "Enable all for authenticated" ON vendas;
DROP POLICY IF EXISTS "Enable all for authenticated" ON venda_itens;

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE estoque_tamanhos ENABLE ROW LEVEL SECURITY;
ALTER TABLE vendas ENABLE ROW LEVEL SECURITY;
ALTER TABLE venda_itens ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all for authenticated" ON profiles FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all for authenticated" ON clients FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all for authenticated" ON products FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all for authenticated" ON estoque_tamanhos FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all for authenticated" ON vendas FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all for authenticated" ON venda_itens FOR ALL USING (auth.role() = 'authenticated');

-- Function to decrement stock safely
CREATE OR REPLACE FUNCTION decrement_stock(row_id UUID, amount INTEGER)
RETURNS VOID AS $$
BEGIN
  UPDATE public.estoque_tamanhos
  SET quantity = quantity - amount
  WHERE id = row_id;
END;
$$ LANGUAGE plpgsql;

-- Initial Settings
INSERT INTO store_settings (id, store_name) VALUES (1, 'Minha Loja de Pijamas') ON CONFLICT DO NOTHING;
`;
