
export interface Migration {
    id: string;
    date: string;
    description: string;
    sql: string;
}

// 1. SCRIPT PARA INSTALAÇÃO DO ZERO (PARA NOVOS CLIENTES - APAGA TUDO!)
export const fullInstallScript = `-- =================================================================
-- OPÇÃO A: INSTALAÇÃO COMPLETA (NOVO CLIENTE - APAGA TUDO!)
-- Use este script para configurar um banco de dados NOVO do zero.
-- =================================================================

-- LIMPEZA
DROP TABLE IF EXISTS public.transactions CASCADE;
DROP TABLE IF EXISTS public.bank_accounts CASCADE;
DROP TABLE IF EXISTS public.venda_itens CASCADE;
DROP TABLE IF EXISTS public.vendas CASCADE;
DROP TABLE IF EXISTS public.estoque_tamanhos CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.clients CASCADE;
DROP TABLE IF EXISTS public.payment_methods CASCADE;
DROP TABLE IF EXISTS public.store_settings CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;
DROP TABLE IF EXISTS public.product_sizes CASCADE;
DROP SEQUENCE IF EXISTS public.sales_seq;
DROP SEQUENCE IF EXISTS public.quotes_seq;
DROP SEQUENCE IF EXISTS public.losses_seq;
DROP FUNCTION IF EXISTS public.get_next_code;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- TABELAS
CREATE TABLE public.profiles (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT DEFAULT 'Gs020185*', 
  role TEXT CHECK (role IN ('admin', 'employee')) DEFAULT 'admin',
  preferences JSONB DEFAULT '{"darkMode": false}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.store_settings (
  id SERIAL PRIMARY KEY,
  store_name TEXT DEFAULT 'PijamaManager Pro',
  theme_color TEXT DEFAULT '#0ea5e9',
  logo_url TEXT,
  max_installments INTEGER DEFAULT 6,
  payment_config JSONB DEFAULT '[]'::jsonb
);

CREATE TABLE public.product_sizes (
  id SERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.payment_methods (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT CHECK (type IN ('credit', 'debit', 'pix', 'cash')),
  rates JSONB DEFAULT '{}'::jsonb,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.products (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  nome TEXT NOT NULL,
  modelo TEXT,
  descricao TEXT,
  categoria TEXT,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.estoque_tamanhos (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  product_id UUID REFERENCES public.products(id) ON DELETE CASCADE,
  model_variant TEXT DEFAULT 'Padrão',
  size TEXT NOT NULL,
  quantity INTEGER DEFAULT 0,
  price_cost DECIMAL(10,2) DEFAULT 0,
  price_sale DECIMAL(10,2) DEFAULT 0,
  sku TEXT,
  reference TEXT,
  CONSTRAINT unique_variant_size UNIQUE (product_id, model_variant, size)
);

CREATE TABLE public.clients (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  full_name TEXT NOT NULL,
  cpf TEXT,
  phone TEXT,
  email TEXT,
  address TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE SEQUENCE public.sales_seq START 1;
CREATE SEQUENCE public.quotes_seq START 1;
CREATE SEQUENCE public.losses_seq START 1;

CREATE OR REPLACE FUNCTION get_next_code(prefix TEXT) RETURNS TEXT AS $$
DECLARE
    next_val INTEGER;
BEGIN
    IF prefix = 'V' THEN
        next_val := nextval('sales_seq');
    ELSIF prefix = 'C' THEN
        next_val := nextval('quotes_seq');
    ELSE
        next_val := nextval('losses_seq');
    END IF;
    RETURN prefix || LPAD(next_val::TEXT, 5, '0');
END;
$$ LANGUAGE plpgsql;

CREATE TABLE public.vendas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT,
  client_id UUID REFERENCES public.clients(id) ON DELETE SET NULL,
  user_id UUID,
  total_value DECIMAL(10,2) NOT NULL,
  payment_method TEXT, 
  payment_status TEXT CHECK (payment_status IN ('paid', 'pending', 'refunded', 'loss')),
  status_label TEXT CHECK (status_label IN ('Venda', 'Condicional', 'Baixa', 'Devolução', 'Convertida')),
  payment_details JSONB,
  observacoes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.venda_itens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id BIGINT REFERENCES public.vendas(id) ON DELETE CASCADE,
  product_variation_id UUID REFERENCES public.estoque_tamanhos(id),
  quantity INTEGER NOT NULL,
  unit_price DECIMAL(10,2) NOT NULL,
  original_cost DECIMAL(10,2)
);

CREATE TABLE public.bank_accounts (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  balance DECIMAL(12,2) DEFAULT 0,
  is_default BOOLEAN DEFAULT FALSE,
  color TEXT DEFAULT '#64748b',
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description TEXT NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  type TEXT CHECK (type IN ('income', 'expense')),
  account_id INTEGER REFERENCES public.bank_accounts(id) ON DELETE SET NULL,
  category TEXT,
  date DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access Profiles" ON profiles FOR ALL USING (true) WITH CHECK (true);
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access Clients" ON clients FOR ALL USING (true) WITH CHECK (true);
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access Products" ON products FOR ALL USING (true) WITH CHECK (true);
ALTER TABLE estoque_tamanhos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access Stock" ON estoque_tamanhos FOR ALL USING (true) WITH CHECK (true);
ALTER TABLE vendas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access Sales" ON vendas FOR ALL USING (true) WITH CHECK (true);
ALTER TABLE venda_itens ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access Items" ON venda_itens FOR ALL USING (true) WITH CHECK (true);
ALTER TABLE payment_methods ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access Payments" ON payment_methods FOR ALL USING (true) WITH CHECK (true);
ALTER TABLE store_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access Settings" ON store_settings FOR ALL USING (true) WITH CHECK (true);
ALTER TABLE bank_accounts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access Accounts" ON bank_accounts FOR ALL USING (true) WITH CHECK (true);
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access Transactions" ON transactions FOR ALL USING (true) WITH CHECK (true);
ALTER TABLE product_sizes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access Sizes" ON product_sizes FOR ALL USING (true) WITH CHECK (true);

-- DADOS INICIAIS
INSERT INTO profiles (id, username, password, role) VALUES ('00000000-0000-0000-0000-000000000000', 'admin', 'Gs020185*', 'admin') ON CONFLICT (id) DO NOTHING;
INSERT INTO store_settings (id, store_name, theme_color) VALUES (1, 'Minha Loja', '#0ea5e9') ON CONFLICT (id) DO NOTHING;
INSERT INTO payment_methods (name, type, rates) VALUES ('Dinheiro', 'cash', '{}'), ('Pix', 'pix', '{}'), ('Débito', 'debit', '{"1": 1.5}'), ('Crédito', 'credit', '{"1": 3.0}') ON CONFLICT DO NOTHING;
INSERT INTO bank_accounts (name, balance, is_default, color) VALUES ('Caixa Loja', 0, true, '#10b981') ON CONFLICT DO NOTHING;

INSERT INTO product_sizes (name, sort_order) VALUES
('RN', 0), ('PB', 1), ('PP', 2), ('P', 3), ('M', 4), ('G', 5), ('GG', 6), ('XG', 7), ('XXG', 8), ('U', 9),
('1', 10), ('2', 11), ('3', 12), ('4', 13), ('6', 14), ('8', 15), ('10', 16), ('12', 17), ('14', 18), ('16', 19)
ON CONFLICT (name) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

// 2. SCRIPT DE CORREÇÃO (PATCH) - NÃO APAGA DADOS
export const patchSizesScript = `-- =================================================================
-- OPÇÃO B: CORREÇÃO / ATUALIZAÇÃO (NÃO APAGA SEUS DADOS!)
-- Use este script para adicionar a tabela de Tamanhos que está faltando.
-- =================================================================

CREATE TABLE IF NOT EXISTS public.product_sizes (
  id SERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.product_sizes ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'product_sizes' AND policyname = 'Public Access Sizes'
    ) THEN
        CREATE POLICY "Public Access Sizes" ON public.product_sizes FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;

INSERT INTO public.product_sizes (name, sort_order) VALUES
('RN', 0), ('PB', 1), ('PP', 2), ('P', 3), ('M', 4), ('G', 5), ('GG', 6), ('XG', 7), ('XXG', 8), ('U', 9),
('1', 10), ('2', 11), ('3', 12), ('4', 13), ('6', 14), ('8', 15), ('10', 16), ('12', 17), ('14', 18), ('16', 19)
ON CONFLICT (name) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

export const dbSetupScript = fullInstallScript;
export const fixSequencesSQL = `-- Correção de Sequências
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP
        IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE c.relname = r.tablename || '_id_seq' AND n.nspname = 'public') THEN
            EXECUTE format('SELECT setval(pg_get_serial_sequence(%L, %L), COALESCE(MAX(id), 0) + 1, false) FROM %I', 'public.' || r.tablename, 'id', r.tablename);
        END IF;
    END LOOP;
END $$;
`;
