
export const dbSetupScript = `
-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- LIMPEZA DE CONSTRAINTS ANTIGAS (PREVENÇÃO DE ERROS)
DO $$ 
BEGIN
    BEGIN
        ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_id_fkey;
    EXCEPTION WHEN undefined_object THEN NULL; END;
    
    BEGIN
        ALTER TABLE public.vendas DROP CONSTRAINT IF EXISTS vendas_user_id_fkey;
    EXCEPTION WHEN undefined_object THEN NULL; END;
END $$;

-- 1. Profiles
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  role TEXT CHECK (role IN ('admin', 'employee')) DEFAULT 'admin',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Store Settings
CREATE TABLE IF NOT EXISTS public.store_settings (
  id SERIAL PRIMARY KEY,
  store_name TEXT DEFAULT 'PijamaManager Pro',
  theme_color TEXT DEFAULT '#0ea5e9',
  logo_url TEXT,
  max_installments INTEGER DEFAULT 6,
  payment_config JSONB DEFAULT '[]'::jsonb
);

-- MIGRATION PARA LOGO_URL
DO $$
BEGIN
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS logo_url TEXT;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;


-- 3. Clients
CREATE TABLE IF NOT EXISTS public.clients (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  full_name TEXT NOT NULL,
  cpf TEXT,
  phone TEXT,
  email TEXT,
  address TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Payment Methods (NOVO)
CREATE TABLE IF NOT EXISTS public.payment_methods (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT CHECK (type IN ('credit', 'debit', 'pix', 'cash')),
  rates JSONB DEFAULT '{}'::jsonb, -- Ex: {"1": 0, "2": 5.0}
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Products
CREATE TABLE IF NOT EXISTS public.products (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  nome TEXT NOT NULL,
  modelo TEXT,
  descricao TEXT,
  categoria TEXT,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Inventory
CREATE TABLE IF NOT EXISTS public.estoque_tamanhos (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  product_id UUID REFERENCES public.products(id) ON DELETE CASCADE,
  model_variant TEXT DEFAULT 'Padrão',
  size TEXT NOT NULL,
  quantity INTEGER DEFAULT 0,
  price_cost DECIMAL(10,2) DEFAULT 0,
  price_sale DECIMAL(10,2) DEFAULT 0,
  sku TEXT,
  reference TEXT
);

-- Migration para model_variant
DO $$
BEGIN
    ALTER TABLE public.estoque_tamanhos ADD COLUMN IF NOT EXISTS model_variant TEXT DEFAULT 'Padrão';
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

-- Constraints de unicidade
DO $$ 
BEGIN
    ALTER TABLE public.estoque_tamanhos DROP CONSTRAINT IF EXISTS unique_product_size;
    ALTER TABLE public.estoque_tamanhos DROP CONSTRAINT IF EXISTS unique_variant_size;
EXCEPTION WHEN undefined_object THEN NULL; END $$;

ALTER TABLE public.estoque_tamanhos ADD CONSTRAINT unique_variant_size UNIQUE (product_id, model_variant, size);

-- 7. SEQUÊNCIAS PARA CÓDIGOS (NOVO)
CREATE SEQUENCE IF NOT EXISTS sales_seq START 1;
CREATE SEQUENCE IF NOT EXISTS quotes_seq START 1;

-- 8. Sales & Quotes
CREATE TABLE IF NOT EXISTS public.vendas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT, -- V0001 ou C0001
  client_id UUID REFERENCES public.clients(id) ON DELETE SET NULL,
  user_id UUID,
  total_value DECIMAL(10,2) NOT NULL,
  payment_method TEXT, 
  payment_status TEXT CHECK (payment_status IN ('paid', 'pending', 'refunded', 'loss')),
  status_label TEXT,
  payment_details JSONB,
  observacoes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- MIGRATION PARA ATUALIZAR STATUS LABEL E COLUNA CODE
DO $$ 
BEGIN 
    ALTER TABLE public.vendas ADD COLUMN IF NOT EXISTS code TEXT;
    ALTER TABLE public.vendas ADD COLUMN IF NOT EXISTS payment_details JSONB;
    
    -- Atualizar Constraint de Status para permitir 'Convertida'
    ALTER TABLE public.vendas DROP CONSTRAINT IF EXISTS vendas_status_label_check;
    ALTER TABLE public.vendas ADD CONSTRAINT vendas_status_label_check 
    CHECK (status_label IN ('Venda', 'Condicional', 'Baixa', 'Devolução', 'Convertida'));

EXCEPTION WHEN OTHERS THEN NULL; 
END $$;

-- 9. Sale Items
CREATE TABLE IF NOT EXISTS public.venda_itens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id BIGINT REFERENCES public.vendas(id) ON DELETE CASCADE,
  product_variation_id UUID REFERENCES public.estoque_tamanhos(id),
  quantity INTEGER NOT NULL,
  unit_price DECIMAL(10,2) NOT NULL,
  original_cost DECIMAL(10,2)
);

-- Função para Gerar Códigos (NOVO)
CREATE OR REPLACE FUNCTION get_next_code(prefix TEXT) RETURNS TEXT AS $$
DECLARE
    next_val INTEGER;
BEGIN
    IF prefix = 'V' THEN
        next_val := nextval('sales_seq');
    ELSE
        next_val := nextval('quotes_seq');
    END IF;
    RETURN prefix || LPAD(next_val::TEXT, 5, '0');
END;
$$ LANGUAGE plpgsql;

-- ==========================================
-- STORAGE CONFIGURATION (UPLOAD DE IMAGENS)
-- ==========================================
-- 1. Create Bucket
INSERT INTO storage.buckets (id, name, public) 
VALUES ('store-assets', 'store-assets', true)
ON CONFLICT (id) DO NOTHING;

-- 2. Storage Policies (Allow Public Read, Allow All Insert/Update for Demo)
DO $$
BEGIN
    -- Drop old policies to ensure idempotency
    DROP POLICY IF EXISTS "Public Access Bucket" ON storage.objects;
    DROP POLICY IF EXISTS "Authenticated Upload" ON storage.objects;
EXCEPTION WHEN OTHERS THEN NULL; END $$;

CREATE POLICY "Public Access Bucket" ON storage.objects FOR SELECT USING ( bucket_id = 'store-assets' );
CREATE POLICY "Authenticated Upload" ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'store-assets' );
CREATE POLICY "Authenticated Update" ON storage.objects FOR UPDATE USING ( bucket_id = 'store-assets' );


-- RLS Policies (ABERTO PARA PÚBLICO/DEMO)
DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Public Access" ON profiles;
    DROP POLICY IF EXISTS "Public Access" ON clients;
    DROP POLICY IF EXISTS "Public Access" ON products;
    DROP POLICY IF EXISTS "Public Access" ON estoque_tamanhos;
    DROP POLICY IF EXISTS "Public Access" ON vendas;
    DROP POLICY IF EXISTS "Public Access" ON venda_itens;
    DROP POLICY IF EXISTS "Public Access" ON payment_methods;
    DROP POLICY IF EXISTS "Public Access" ON store_settings;
EXCEPTION WHEN undefined_object THEN NULL; END $$;

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE estoque_tamanhos ENABLE ROW LEVEL SECURITY;
ALTER TABLE vendas ENABLE ROW LEVEL SECURITY;
ALTER TABLE venda_itens ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_methods ENABLE ROW LEVEL SECURITY;
ALTER TABLE store_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Access" ON profiles FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON clients FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON products FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON estoque_tamanhos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON vendas FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON venda_itens FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON payment_methods FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON store_settings FOR ALL USING (true) WITH CHECK (true);

-- Insert Demo Data
INSERT INTO profiles (id, username, role) VALUES ('00000000-0000-0000-0000-000000000000', 'admin_demo', 'admin') ON CONFLICT (id) DO NOTHING;
INSERT INTO store_settings (id, store_name, theme_color) VALUES (1, 'Minha Loja de Pijamas', '#0ea5e9') ON CONFLICT DO NOTHING;

-- Insert Default Payment Methods
INSERT INTO payment_methods (name, type, rates) VALUES 
('Dinheiro', 'cash', '{}'),
('Pix', 'pix', '{}'),
('Cartão Débito', 'debit', '{"1": 1.5}'),
('Cartão Crédito', 'credit', '{"1": 3.0, "2": 4.5, "3": 5.0}')
ON CONFLICT DO NOTHING;
`;